### ISSUE TITLE
comma discord

### ISSUE THREAD

**Issue by kubsztal** [roxasthenobody98/roxasthenobody98#1]
Why have you suddenly disappeared? Ban?

**Comment by roxasthenobody98** [comment]
Yep. I was banned for wrongthink. I can send you a link to our new server if you want to add me on Discord.

**Comment by kubsztal** [comment]
Sure, please give me a link.

**Comment by roxasthenobody98** [comment]
https://discord.gg/BRJCa9P2

**Comment by kubsztal** [comment]
Expired. One more time, please?

**Comment by roxasthenobody98** [comment]
https://discord.gg/CY88jvkk

**Comment by kubsztal** [comment]
I'm in, thanks.
